# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0002_auto_20180122_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
