# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-23 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0003_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
    ]
