# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0004_auto_20180123_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=200, null=True)),
                ('mark', models.IntegerField(default=0)),
                ('internal', models.IntegerField(default=0)),
                ('internmaxi', models.IntegerField(default=0)),
                ('maxi', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('res', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='intern1',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='intern1max',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='mark1',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='max1',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='res1',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='semid',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='sub1',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='total',
        ),
        migrations.RemoveField(
            model_name='univresults',
            name='total1',
        ),
        migrations.AlterField(
            model_name='univresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sappsapp.Univresults'),
        ),
    ]
