# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0007_attendexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileparent',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sappsapp.Profilechild'),
            preserve_default=False,
        ),
    ]
