# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sappsapp', '0008_profileparent_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileparent',
            name='student',
        ),
    ]
